api:
  dashboard: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure

  websecure:
    address: ":443"
    http:
      middlewares:
        - secureHeaders@file
      tls:
        certResolver: ${CERTRESOLVER}

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: /configurations/dynamic.yml

certificatesResolvers:
  letsencrypt-staging:
    acme:
      email: me@junaid.guru
      storage: acme.json
      tlsChallenge: true
      caserver: https://acme-staging-v02.api.letsencrypt.org/directory
      keyType: EC384
  letsencrypt:
    acme:
      email: me@junaid.guru
      storage: acme.json
      keyType: EC384
      httpChallenge:
        entryPoint: web
