name: Call a reusable workflow

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get necessary binaries from cache
        uses: actions/cache@v2
        with:
          path: |
            /usr/local/bin/docker-compose,
            /usr/local/bin/yq
          key: ${{ runner.os }}-binaries-v1

      - name: Download required binaries
        run: |
          if ! command -v docker-compose &> /dev/null; then
            curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
          fi
          
          if ! command -v yq &> /dev/null; then
            curl -sSL "https://github.com/mikefarah/yq/releases/download/v4.13.3/yq_linux_amd64" -o /usr/local/bin/yq
            chmod +x /usr/local/bin/yq
          fi

      - name: Print Environment Variables
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY}}
          TEST_KEY: ${{ secrets.TEST_KEY }}
        run: |
          echo "Environment Variables:"
          printenv
          
          ls -l
          
          yq
