name: Call a reusable workflow

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install yq
        run: |
          curl -sSL -o /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.13.3/yq_linux_amd64
          chmod +x /usr/local/bin/yq
      - name: Print Environment Variables
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY}}
          TEST_KEY: ${{ secrets.TEST_KEY }}
        run: |
          echo "Environment Variables:"
          printenv
          
          ls -l
          
          yq
