name: Call a reusable workflow

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Print Environment Variables
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY}}
          TEST_KEY: ${{ secrets.TEST_KEY }}
        run: |
          echo "Environment Variables:"
          printenv
          
          ls -l
