name: Call a reusable workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Print Environment Variables
        run: |
          echo "Environment Variables:"
          printenv
          
          ls -l
